//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvMvcClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTable
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string FinancialYear { get; set; }
        public int StartMonth { get; set; }
        public int EndMonth { get; set; }
        public string LastUpdateDate { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
