//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvMvcClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingCategoryTable
    {
        public BillingCategoryTable()
        {
            this.CustomerDetailsTables = new HashSet<CustomerDetailsTable>();
        }
    
        public int ID { get; set; }
        public string CategoryCode { get; set; }
        public int Amount { get; set; }
        public int Frequency { get; set; }
        public int OldID { get; set; }
        public string BillingPlan { get; set; }
    
        public virtual BillingFrequncyTable BillingFrequncyTable { get; set; }
        public virtual ICollection<CustomerDetailsTable> CustomerDetailsTables { get; set; }
    }
}
