//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaDetailsTable
    {
        public AreaDetailsTable()
        {
            this.AgentDetailsTables = new HashSet<AgentDetailsTable>();
            this.LedgerTables = new HashSet<LedgerTable>();
            this.CustomerDetailsTables = new HashSet<CustomerDetailsTable>();
        }
    
        public int ID { get; set; }
        public int AreaCode { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<AgentDetailsTable> AgentDetailsTables { get; set; }
        public virtual ICollection<LedgerTable> LedgerTables { get; set; }
        public virtual ICollection<CustomerDetailsTable> CustomerDetailsTables { get; set; }
    }
}
