//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileCollection
    {
        public int Id { get; set; }
        public int RecieptNo { get; set; }
        public int CustomerId { get; set; }
        public int Amount { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int EmpId { get; set; }
        public string GpsLocation { get; set; }
        public string LedgerUpdated { get; set; }
    }
}
