//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvMvcClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingFrequncyTable
    {
        public BillingFrequncyTable()
        {
            this.BillingCategoryTables = new HashSet<BillingCategoryTable>();
        }
    
        public int ID { get; set; }
        public string FrequncyName { get; set; }
        public int NumberOfMonths { get; set; }
    
        public virtual ICollection<BillingCategoryTable> BillingCategoryTables { get; set; }
    }
}
