//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTable
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public int CustCode { get; set; }
        public int AreaCode { get; set; }
        public string AgentCode { get; set; }
        public int OldBalance { get; set; }
        public int NumOfMonthsBal { get; set; }
        public int TotalBalance { get; set; }
        public int TotalAmtPaid { get; set; }
        public string Bill_1 { get; set; }
        public string Bill_2 { get; set; }
        public string Bill_3 { get; set; }
        public string Bill_4 { get; set; }
        public string Bill_5 { get; set; }
        public string Bill_6 { get; set; }
        public string Bill_7 { get; set; }
        public string Bill_8 { get; set; }
        public string Bill_9 { get; set; }
        public string Bill_10 { get; set; }
        public string Bill_11 { get; set; }
        public string Bill_12 { get; set; }
        public string Amt_1 { get; set; }
        public string Amt_2 { get; set; }
        public string Amt_3 { get; set; }
        public string Amt_4 { get; set; }
        public string Amt_5 { get; set; }
        public string Amt_6 { get; set; }
        public string Amt_7 { get; set; }
        public string Amt_8 { get; set; }
        public string Amt_9 { get; set; }
        public string Amt_10 { get; set; }
        public string Amt_11 { get; set; }
        public string Amt_12 { get; set; }
        public string Date_1 { get; set; }
        public string Date_2 { get; set; }
        public string Date_3 { get; set; }
        public string Date_4 { get; set; }
        public string Date_5 { get; set; }
        public string Date_6 { get; set; }
        public string Date_7 { get; set; }
        public string Date_8 { get; set; }
        public string Date_9 { get; set; }
        public string Date_10 { get; set; }
        public string Date_11 { get; set; }
        public string Date_12 { get; set; }
        public string Bal_1 { get; set; }
        public string Bal_2 { get; set; }
        public string Bal_3 { get; set; }
        public string Bal_4 { get; set; }
        public string Bal_5 { get; set; }
        public string Bal_6 { get; set; }
        public string Bal_7 { get; set; }
        public string Bal_8 { get; set; }
        public string Bal_9 { get; set; }
        public string Bal_10 { get; set; }
        public string Bal_11 { get; set; }
        public string Bal_12 { get; set; }
    
        public virtual AgentDetailsTable AgentDetailsTable { get; set; }
        public virtual AreaDetailsTable AreaDetailsTable { get; set; }
    }
}
