//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTVTransact
    {
        public int ID { get; set; }
        public int TransactId { get; set; }
        public int ReceiptNo { get; set; }
        public string AccountNo { get; set; }
        public int CollectionAmount { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int InstalmentAmount { get; set; }
        public string Cancel { get; set; }
        public string AgentCode { get; set; }
        public string CollectionTime { get; set; }
        public string LedgerUpdated { get; set; }
    }
}
