//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActvMvcClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetailsTable
    {
        public CustomerDetailsTable()
        {
            this.AmountCollectionTables = new HashSet<AmountCollectionTable>();
        }
    
        public int ID { get; set; }
        public int CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string AgentCode { get; set; }
        public int AreaCode { get; set; }
        public string BillingCategory { get; set; }
        public string Address { get; set; }
        public string MobileNum { get; set; }
        public string ConnectionDate { get; set; }
        public int InitialBalance { get; set; }
        public bool Active { get; set; }
        public string Comments { get; set; }
    
        public virtual AgentDetailsTable AgentDetailsTable { get; set; }
        public virtual ICollection<AmountCollectionTable> AmountCollectionTables { get; set; }
        public virtual AreaDetailsTable AreaDetailsTable { get; set; }
        public virtual BillingCategoryTable BillingCategoryTable { get; set; }
    }
}
